### ISSUE TITLE
How install this plugin? 

### ISSUE THREAD

**Issue by samuk190** [kvidelov/hardware-monitor-kv#1]
I couldnt understand the documentation

**Comment by kaloyanvi** [comment]
Did you succeed setting it up? Else I can try helping you.

**Comment by samuk190** [comment]
> Did you succeed setting it up? Else I can try helping you.

yes but the script are outdated, not showing info correctly because nvidia-smi updated sometime ago. 
maybe improve script to find specific strings, like (C) which means celsius, so get 2 char before C or something like that that would be future update proof
